# Generated by Django 3.0.4 on 2020-06-16 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200615_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='rating',
            new_name='ratin',
        ),
    ]
