# Generated by Django 3.0.4 on 2020-06-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200616_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='IMG_4016.jpg', upload_to='uploads/'),
        ),
    ]
