# Generated by Django 3.0.4 on 2020-06-19 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_answer_dislike_like_question_tag_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dislike',
            name='question',
        ),
        migrations.RemoveField(
            model_name='dislike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='question',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='asking',
        ),
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Dislike',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
