# Generated by Django 3.0.4 on 2020-06-19 11:16

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_answer_dislike_like_myuser_question_tag'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', app.models.myUManager()),
            ],
        ),
    ]
