# Generated by Django 3.0.4 on 2020-06-19 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200619_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='asking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asking', to='app.myUser'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(related_name='tagn', to='app.Tag'),
        ),
    ]
